# Generated by Django 4.0.5 on 2022-07-01 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Marca')),
                ('stock', models.IntegerField(max_length=6, verbose_name='Stock')),
                ('precio', models.IntegerField(max_length=14, verbose_name='Precio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/core/imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('idPromocion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('nombrepro', models.CharField(max_length=100, verbose_name='Nombre')),
                ('porcDesceunto', models.IntegerField(max_length=14, verbose_name='Precio')),
                ('precioFinal', models.IntegerField(max_length=14, verbose_name='Precio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
    ]
