# Generated by Django 4.0.5 on 2022-07-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_precio_alter_producto_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=50, verbose_name='descripcion'),
        ),
    ]
