# Generated by Django 4.0.5 on 2022-07-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='porcDesceunto',
            field=models.IntegerField(verbose_name='Porcentaje de descuento'),
        ),
    ]
