# Generated by Django 4.0.5 on 2022-07-02 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_promocion_porcdesceunto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocion',
            old_name='producto',
            new_name='idProducto',
        ),
    ]
